### PR TITLE
(theme): use cosmic-theme for all widgets

### PR DESCRIPTION
**Pull request by wash2**
This modifies libcosmic to use cosmic-theme internally.

### CODE REVIEW

**Review by 13r0ck — COMMENTED** [review]
Is there any reason for us to call it `cosmic-container`? I would rather just import a single container widget

**Comment by wash2** [comment]
> Is there any reason for us to call it `cosmic-container`? I would rather just import a single container widget

I called it CosmicContainer because it is deferent and not meant to be used all the time, only really to denote a layer. Normal containers are still useful, but I'm open to another name than CosmicContainer.

**Comment by 13r0ck** [comment]
Why is it not meant to be used all the time?

**Comment by 13r0ck** [comment]
I think it might be more ergonomic to just overwrite the container import all together and just have our cosmic `container` widget just have a method to denote layer

**Comment by wash2** [comment]
> I think it might be more ergonomic to just overwrite the container import all together and just have our cosmic `container` widget just have a method to denote layer

Ok I could probably do that

**Review by 13r0ck — APPROVED** [review]
Thank you!!!

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
