### PR TITLE
WIP: Update to 0.12

### PR DESCRIPTION
**Pull request by wash2**
cosmic-time still needs to be updated. Most of libcosmic is working well now, but I'm still looking into a small layout issue for dropdown menu items, and also a color picker tooltip. It panics when interacting with the tooltip after interacting with the color picker previously.

### CODE REVIEW

**Comment by wash2** [comment]
Everything seems to be working alright now, so this should be ready for review.
I will start updating some applications and applets to see if we need any more changes too.

https://github.com/pop-os/iced/pull/85
https://github.com/pop-os/cosmic-time/pull/17

**Comment by wash2** [comment]
The launcher window is very small when testing.

**Comment by mmstick** [comment]
Seems fine. There is one change that I noticed in the design demo. The width of the debug toggle, using cosmic-time's toggler, now defaults to `Length::Shrink` rather than `Length::Fill` now.

**Comment by wash2** [comment]
> Seems fine. There is one change that I noticed in the design demo. The width of the debug toggle, using cosmic-time's toggler, now defaults to `Length::Shrink` rather than `Length::Fill` now.

Ok, should I change that? I had to change the method for the layout of the toggler in cosmic-time, which is probably what causes the difference.

**Comment by mmstick** [comment]
We can adjust it in the design-demo

**Review by mmstick — APPROVED** [review]

**Pull request merged**
